version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - HOST=0.0.0.0
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "120", "app:app"]  # Increase timeout to 120s
    networks:
      - app-network
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge